services:
  counter:
    image: ubuntu:26.04
    networks:
      frontend:
        ipv4_address: 192.168.0.1
      backend:
        ipv4_address: 192.168.1.1
    ports:
      - "127.0.0.1:8000-8009:80"
  api:
    image: ubuntu:26.04
    networks:
      backend:
        ipv4_address: 192.168.1.2
    ports:
      - "127.0.0.1:8010-8019:80"
  admin:
    image: ubuntu:26.04
    networks:
      backend:
        ipv4_address: 192.168.1.3
    ports:
      - "127.0.0.1:8020-8029:80"
networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.254
  backend:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.254
