FROM ubuntu:resolute
EXPOSE 80

RUN apt update
RUN apt install -y nginx php-fpm
RUN rm /etc/nginx/conf.d/default.conf

ADD ./etc/nginx/docker/nginx.conf /etc/nginx/nginx.conf
ADD ./var/www/index.php /var/www/index.php

RUN groupadd nginx
RUN useradd -g nginx nginx
CMD nginx -g "daemon off;"
