FROM ubuntu:resolute
EXPOSE 80

ADD ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./etc/php/8.5/fpm/php.conf /etc/php/8.5/fpm/php.conf
ADD ./www/counter/index.php /var/www/counter/index.php

RUN apt update
RUN apt install -y nginx php-fpm
