FROM nginx:1.31.5
EXPOSE 80

RUN apt update
RUN apt install -y nginx
RUN mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old

ADD ./etc/nginx/proxy/nginx.conf /etc/nginx/nginx.conf
CMD nginx -g "daemon off;"
