FROM ubuntu:resolute
EXPOSE 80

RUN apt update
RUN apt install -y nginx php-fpm
RUN systemctl enable nginx
RUN systemctl start nginx
RUN systemctl enable php8.5-fpm
RUN systemctl start php8.5-fpm

ADD ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./var/www/index.php /var/www/index.php
