FROM ubuntu:resolute as counter
EXPOSE 80

ADD ./etc/nginx/nginx.conf /etc/nginx/nginx.conf
ADD ./etc/php/8.5/fpm/php.conf /etc/php/8.5/fpm/php.conf
ADD ./var/www/index.php /var/www/index.php

RUN apt update
RUN apt install -y nginx php-fpm
RUN systemctl enable nginx
RUN systemctl start nginx
RUN systemctl enable php8.5-fpm
RUN systemctl start php8.5-fpm
