name: Testing Network
on:
  workflow_run:
    workflows: [Service Containers]
    types: [completed]
jobs:
  nc:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Running netcat to service containers
    runs-on: ubuntu-24.04
    steps:
      - id: install-netcat
        name: Installing netcat-traditional
        run: |
          sudo apt update
          sudo apt install -y netcat-traditional
          alias nc=nc.traditional
      - id: checkout
        name: Checkout
        uses: actions/checkout@v7
      - id: compose-up
        name: Compose up
        run: |
          # 何故かワークフローの中で直近のネットワークが生き残る(キャッシュしてないのに・・・)
          docker compose down --volumes --remove-orphans
          docker network prune -f

          docker compose up -d
      - id: test-counter
        name: With the counters
        run: |
          nc -z 127.0.0.1 8000

          # Dockerネットワーク構築完了を確実に待機
          sleep 3

          curl http://127.0.0.1:8000
      - id: test-api
        name: With the api
        run: |
          ! nc -z 127.0.0.1 8001
      - id: test-admin
        name: With the admin
        run: |
          ! nc -z 127.0.0.1 8002
      - id: install-nginx
        name: Installing Nginx
        run: |
          sudo apt install -y nginx
          sudo rm /etc/nginx/sites-available/default
          sudo rm /etc/nginx/sites-enabled/default
          sudo cp -f ./etc/nginx/proxy/nginx.conf /etc/nginx/nginx.conf
          sudo systemctl restart nginx
      - id: test-proxy
        name: With the proxy
        run: |
          nc -z 127.0.0.1 80
          curl http://127.0.0.1
      - id: check-journal
        name: Checking journal logs
        if: ${{ failure() }}
        run: |
          sudo journalctl -xeu nginx.service
          docker compose logs counter
      - id: compose-down
        name: Compose down
        if: ${{ always() }}
        run: docker compose down
