name: Making sure netcat connections with service containers
on: push
jobs:
  nc:
    name: Compose service containers
    runs-on: ubuntu-24.04
    steps:
      - id: install-netcat
        name: Installing netcat-traditional
        run: |
          sudo apt update
          sudo apt install -y netcat-traditional
          alias nc=nc.traditional
      - id: checkout
        name: Checkout
        uses: actions/checkout@v7
      - id: compose-up
        name: Compose up
        run: docker compose up
      - id: netcat-counter
        name: With the counters
        run: |
          nc -z 192.168.0.1 8000-8999
          nc -z 192.168.1.1 8000-8999
      - id: netcat-api
        name: With the api
        run: nc -z 192.168.1.2 8000-8999
      - id: netcat-admin
        name: With the admin
        run: nc -z 192.168.1.3 8000-8999
      - id: compose-down
        name: Compose down
        if: ${{ always() }}
        run: docker compose down
