name: NetCat
on:
  workflow_run:
    workflows: [Service Containers]
    types: [completed]
jobs:
  nc:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Running netcat to service containers
    runs-on: ubuntu-24.04
    steps:
      - id: install-netcat
        name: Installing netcat-traditional
        run: |
          sudo apt update
          sudo apt install -y netcat-traditional
          alias nc=nc.traditional
      - id: checkout
        name: Checkout
        uses: actions/checkout@v7
      - id: compose-up
        name: Compose up
        run: docker compose up
      - id: netcat-counter
        name: With the counters
        run: |
          nc -z 127.0.0.1 8000-8009
      - id: netcat-api
        name: With the api
        run: nc -z 127.0.0.1 8010-8019
      - id: netcat-admin
        name: With the admin
        run: nc -z 127.0.0.1 8020-8029
      - id: compose-down
        name: Compose down
        if: ${{ always() }}
        run: docker compose down
