name: Testing ICMP request to service containers
on: push
jobs:
  icmp:
    name: Compose service containers
    runs-on: ubuntu-24.04
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v7
      - id: compose
        name: Run Docker compose
        run: docker compose up
      - id: ping-counter
        name: Send a Ping request to the counter host
        run: |
          ping -c 1 127.0.0.1
          ping -c 1 127.0.1.1
      - id: ping-api
        name: Send a Ping request to the api host
        run: ping -c 1 127.0.1.2
      - id: ping-admin
        name: Send a Ping request to the admin host
        run: ping -c 1 127.0.1.3
